# -*- coding: utf-8 -*-
"""lesson_7_homework

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1BA2uUsMfjwsPCaneKUv-O2BSWikbLlAN
"""



"""# task2  (lesson7)
* oracle: https://leetcode.com/problems/duplicate-emails/






"""

select distinct email from person group by email having count(email) >= 2

"""# task3  (lesson7)
* oracle: https://leetcode.com/problems/employees-earning-more-than-their-managers/
"""

select Employee.name AS Employee 
from Employee 
left join Employee AS managers
on Employee.managerId = managers.id
where Employee.salary > managers.salary

"""# task4  (lesson7)
* oracle: https://leetcode.com/problems/rank-scores/
"""

WITH unique_scores AS
(
    select DISTINCT score FROM Scores
),
unique_ranks AS
(
    select score, RANK() OVER(ORDER BY score DESC) AS "rank"
    from unique_scores
    order by score DESC
)
select Scores.score, unique_ranks.rank from Scores
left join unique_ranks
on Scores.score = unique_ranks.score
order by Scores.score DESC

"""# task5  (lesson7)
* oracle: https://leetcode.com/problems/combine-two-tables/
"""

select firstName, lastName, city, state FROM Person
left join Address
on Person.personId = Address.personId

