# -*- coding: utf-8 -*-
"""lesson_6_homework

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1XEPRa_S5hVOwhOxpDw2isqliMKjD8f22
"""

#установка библиотек
!pip install -U psycopg2
!pip install -U plotly

import psycopg2
psycopg2.__version__

"""# проверка подключения"""

# student11
# student11_password

#проверка подключения PostgreSQL 
import psycopg2
import pandas as pd
#Библиотека ждя визуализации
from IPython.display import HTML
import plotly.express as px


#!введите свои реквизиты!
DB_HOST = '52.157.159.24'
DB_USER = 'student11'
DB_USER_PASSWORD = 'student11_password'
DB_NAME = 'sql_ex_third_stream'

conn = psycopg2.connect(host=DB_HOST, user=DB_USER, password=DB_USER_PASSWORD, dbname=DB_NAME)

conn

conn.isexecuting()

"""# задания

# task1  (lesson6, дополнительно)
* SQL: Создайте таблицу с синтетическими данными (10000 строк, 3 колонки, все типы int) и заполните ее случайными данными от 0 до 1 000 000. Проведите EXPLAIN операции и сравните базовые операции.
"""

SQL1 =  """
            DROP TABLE IF EXISTS synthetic_11
            ;

            CREATE TABLE synthetic_11
            (
                column_01 int,
                column_02 int,
                column_03 int
            )
            ;

            INSERT INTO synthetic_11(column_01, column_02, column_03)
            SELECT 
                1000000 * random(), 
                1000000 * random(), 
                1000000 * random()
            FROM generate_series(0, 10000 - 1)
            ;

            SELECT * 
            FROM synthetic_11
            ;
         """

df = pd.read_sql_query(SQL1, conn)
df

# df.to_csv('df.csv')

SQL1 =  """
            EXPLAIN ANALYZE

            SELECT * 
            FROM synthetic_11
            ;

        """

df = pd.read_sql_query(SQL1, conn)
df['QUERY PLAN'][0]

SQL1 =  """
            EXPLAIN ANALYZE

            INSERT INTO synthetic_11 (column_01, column_02, column_03)
            VALUES (1,2,3)
            ;

        """

df = pd.read_sql_query(SQL1, conn)
df['QUERY PLAN'][0]

SQL1 =  """
            EXPLAIN ANALYZE

            DELETE FROM synthetic_11
            WHERE 
                column_01 = 1 AND 
                column_02 = 2 AND 
                column_03 = 3
            ;

        """

df = pd.read_sql_query(SQL1, conn)
df['QUERY PLAN'][0]



"""# task2 (lesson6, дополнительно)
* GCP (Google Cloud Platform): Через GCP загрузите данные csv в базу PSQL по личным реквизитам (используя только bash и интерфейс bash)

```
wget --no-check-certificate 'https://docs.google.com/uc?export=download&id=1UbCdRr0li6gFM0E2TsuW5gOPiEGLTQTC' -O ships.csv
```


```
select count(1) from ships;
 count
-------
    44
(1 row)
```



```
\COPY ships FROM './ships.csv' delimiter ',' csv header ;
COPY 22
```

```
select count(1) from ships;
 count
-------
    66
(1 row)
```
"""





